[package]
name = "frr_bgp_watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0.26", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
env_logger = "0.9"
log = "0.4"

[profile]
release = { strip = "symbols", lto = "thin", opt-level = "z" }